### ISSUE TITLE
Bug in dashboard.html, JSON parse error

### ISSUE THREAD

**Issue by swghosh** [thealphadollar/messiah#53]
## Minor bug in src/frontend/dashboard.html

The JavaScript console when loading the dashboard, reports error.
```
[Error] SyntaxError: JSON Parse error: Unexpected EOF
	parse (dashboard.html:228)
	onreadystatechange (dashboard.html:228)
[Error] TypeError: undefined is not an object (evaluating 'data["results"][0]["geometry"]')
	onreadystatechange (dashboard.html:229)
[Error] SyntaxError: JSON Parse error: Unexpected EOF
	parse (dashboard.html:199)
	onreadystatechange (dashboard.html:199)
```

### Problem

The javascript code snippet uses two AJAX requests to get JSON(s) from the backend server. Although, the backend API server returns JSON in correct form, error is raised during parse at client-side.

### Workaround

**Relevant fix**
request's function ```onreadystatechange``` should check for ```this.status == 4 && this.status == 200``` and only then perform further actions 
- https://github.com/thealphadollar/messiah/blob/3927781ee628f4a4c928095b34f512c5c376ce2b/src/frontend/dashboard.html#L197-L204
- https://github.com/thealphadollar/messiah/blob/3927781ee628f4a4c928095b34f512c5c376ce2b/src/frontend/dashboard.html#L227-L234

Refer to: https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX/Getting_Started#Step_3_–_A_Simple_Example

**Comment by knightcube** [comment]
May I work on this?

**Comment by theartist007** [comment]
Actually, this issue is labeled KWOC, which means we have put it for students of Kharagpur Winter of Code program, to solve. U can surely be a part of KWOC, and then solve this, if you already aren't.

**Comment by knightcube** [comment]
Yes I am a participant of KWOC. Could you please tell me how can I fix this issue?

**Comment by theartist007** [comment]
@swghosh has written a possible fix of the issue, in the description. You can go on his lines, or think about it yourself how to do it. The README.md file has the complete description of the project.

**Comment by knightcube** [comment]
I read the suggested fix and I am implementing it. Kindly tell me if I am going wrong. This is what i am doing currently - 
1) 1st if block contains Lines 197 to 204
2) 2nd if block would contain Lines 227 to 234
and the if condition will be - if(this.status == 4 && this.status == 200)

**Comment by swghosh** [comment]
Absolutely @knightcube
Just test it once whether the bug is fixed after that or not. There's a reference link too.

**Comment by theartist007** [comment]
Yes @knightcube , its absolutely fine. Go for it. 
U can join my kwoc project channel : https://gitter.im/kwoc-messiah/Lobby, if you want to work further, on this project.

**Comment by knightcube** [comment]
Already there :)
