### ISSUE TITLE
Dashboard front end is not responsive

### ISSUE THREAD

**Issue by knightcube** [thealphadollar/messiah#56]
Bug
Expanding the screen size makes the Prediction table to go down. 
Contracting the screen size makes Prediction table to stay in position

Expected Behaviour
Expanding the screen size should make the Prediction table to stay in position

Attaching screenshots below. Please take a look

![screenshot 52](https://user-images.githubusercontent.com/22871961/49581820-3330df00-f979-11e8-8946-2327dd4f8d04.png)
![screenshot 53](https://user-images.githubusercontent.com/22871961/49581823-34620c00-f979-11e8-88cf-7d3dab0bc346.png)

**Comment by swghosh** [comment]
Changing the css style height for the div map should fix this.
https://github.com/thealphadollar/messiah/blob/master/src/frontend/css/style.css
